services:
  novellia-postgres:
    image: postgres:13
    container_name: novellia-postgres
    environment:
      POSTGRES_DB: ${DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  novellia-backend:
    build: ./backend
    container_name: backend
    environment:
      DATABASE: ${DATABASE}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
      DB_HOST: novellia-postgres
      PG_PORT: ${PG_PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - '5000:5000'
    depends_on:
      - novellia-postgres
    profiles:
      - backend

  novellia-frontend:
    container_name: frontend
    image: nextapp:1.0.0
    build:
      context: ./frontend
      dockerfile: next.dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - novellia-backend
    profiles:
      - frontend

volumes:
  pgdata: {}
